# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tracingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TracingDialog(object):
    def setupUi(self, TracingDialog):
        TracingDialog.setObjectName("TracingDialog")
        TracingDialog.resize(549, 578)
        self.buttonBox = QtWidgets.QDialogButtonBox(TracingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 510, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tracing_label = QtWidgets.QLabel(TracingDialog)
        self.tracing_label.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.tracing_label.setObjectName("tracing_label")
        self.tracing_file_button = QtWidgets.QPushButton(TracingDialog)
        self.tracing_file_button.setGeometry(QtCore.QRect(360, 60, 113, 32))
        self.tracing_file_button.setObjectName("tracing_file_button")
        self.tracing_input_path = QtWidgets.QLineEdit(TracingDialog)
        self.tracing_input_path.setGeometry(QtCore.QRect(80, 60, 271, 31))
        self.tracing_input_path.setObjectName("tracing_input_path")

        self.retranslateUi(TracingDialog)
        self.buttonBox.accepted.connect(TracingDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(TracingDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TracingDialog)

    def retranslateUi(self, TracingDialog):
        _translate = QtCore.QCoreApplication.translate
        TracingDialog.setWindowTitle(_translate("TracingDialog", "Dialog"))
        self.tracing_label.setText(_translate("TracingDialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Step 1: Tracing</span></p></body></html>"))
        self.tracing_file_button.setText(_translate("TracingDialog", "Input File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TracingDialog = QtWidgets.QDialog()
    ui = Ui_TracingDialog()
    ui.setupUi(TracingDialog)
    TracingDialog.show()
    sys.exit(app.exec_())
